# rpc_config.yaml
service: "SakataOnEsp32"

functions:
  - name: "fillDisplayMem"
    return_type: "void"
    parameters:
      - name: "data"
        type: "uint8_t[4736]"  # Length of the bitmap

  - name: "setDisplayMem"
    return_type: "void"
    parameters:
      - name: "xIndex"
        type: "int32_t"
      - name: "yIndex"
        type: "int32_t"
      - name: "value"
        type: "int32_t"

  - name: "refreshDisplay"
    return_type: "void"
    parameters:
      - name: "mode"           # 0 -> full refresh, 1 -> partial refresh
        type: "uint8_t"  
    
  - name: "directlyDisplay"
    return_type: "void"
    parameters:
      - name: "data"
        type: "uint8_t[4736]"  # Length of the bitmap
      - name: "mode"           # 0 -> full refresh, 1 -> partial refresh
        type: "uint8_t"

  - name: "fillAndRefresh"
    return_type: "void"
    parameters:
      - name: "data"
        type: "uint8_t[4736]"  # Length of the bitmap
      - name: "mode"           # 0 -> full refresh, 1 -> partial refresh
        type: "uint8_t"

  - name: "setLed"
    return_type: "void"
    parameters:
      - name: "rVal"
        type: "uint8_t"
      - name: "gVal"
        type: "uint8_t"
      - name: "bVal"
        type: "uint8_t"

  - name: "getStatus"
    return_type: "int32_t"
    parameters: []